// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuentinhasDoBill.Data;

#nullable disable

namespace QuentinhasDoBill.Migrations
{
    [DbContext(typeof(QuentinhasDoBillContext))]
    partial class QuentinhasDoBillContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("QuentinhasDoBill.Models.Carrinho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.HasKey("Id")
                        .HasName("PrimaryKey_CarrinhoId");

                    b.ToTable("carrinho");
                });

            modelBuilder.Entity("QuentinhasDoBill.Models.ItemPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("PedidoId")
                        .HasColumnType("int");

                    b.Property<int>("QuentinhaId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PrimaryKey_ItemPedidoId");

                    b.HasIndex("PedidoId");

                    b.HasIndex("QuentinhaId");

                    b.ToTable("itens_pedido");
                });

            modelBuilder.Entity("QuentinhasDoBill.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Canceled")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("Id")
                        .HasName("PrimaryKey_PedidoId");

                    b.ToTable("pedidos");
                });

            modelBuilder.Entity("QuentinhasDoBill.Models.Quentinha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CarrinhoId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("TipoId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PrimaryKey_QuentinhaId");

                    b.HasIndex("CarrinhoId");

                    b.HasIndex("TipoId");

                    b.ToTable("quentinhas");
                });

            modelBuilder.Entity("QuentinhasDoBill.Models.Tipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PrimaryKey_TipoId");

                    b.ToTable("tipos");
                });

            modelBuilder.Entity("QuentinhasDoBill.Models.ItemPedido", b =>
                {
                    b.HasOne("QuentinhasDoBill.Models.Pedido", null)
                        .WithMany("Itens")
                        .HasForeignKey("PedidoId");

                    b.HasOne("QuentinhasDoBill.Models.Quentinha", "Quentinha")
                        .WithMany()
                        .HasForeignKey("QuentinhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quentinha");
                });

            modelBuilder.Entity("QuentinhasDoBill.Models.Quentinha", b =>
                {
                    b.HasOne("QuentinhasDoBill.Models.Carrinho", null)
                        .WithMany("Quentinhas")
                        .HasForeignKey("CarrinhoId");

                    b.HasOne("QuentinhasDoBill.Models.Tipo", null)
                        .WithMany("Quentinhas")
                        .HasForeignKey("TipoId");
                });

            modelBuilder.Entity("QuentinhasDoBill.Models.Carrinho", b =>
                {
                    b.Navigation("Quentinhas");
                });

            modelBuilder.Entity("QuentinhasDoBill.Models.Pedido", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("QuentinhasDoBill.Models.Tipo", b =>
                {
                    b.Navigation("Quentinhas");
                });
#pragma warning restore 612, 618
        }
    }
}
